package com.lattice.exception;
/**
 * This class replaces standard try catch block by automatically handling all the exceptions that are thrown in project.
 * MDC attaches a key value pair to the current thread which is used for Logging data when any Exception occurs
 * Default Logger "logger" is generated by @Log4j Lombok annotation.
 */

import org.json.simple.JSONObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;


@ControllerAdvice
public class ExceptionHandlers  extends ResponseEntityExceptionHandler {

    //Only the exceptions that are specified here will be handled by this particular method.
    // More methods can be added if different actions need to be taken for different Exceptions

    /*
    Handles Exceptions
     */
    @ExceptionHandler({
            Exception.class
    })
    @ResponseStatus(HttpStatus.NOT_IMPLEMENTED)
    public ResponseEntity<Object> GeneralExceptionHandler(Exception e)   {
        JSONObject error = new JSONObject();
        error.put("message" , "Something went wrong. Please contact your administration");
        return new ResponseEntity<>(error.toString(),HttpStatus.NOT_IMPLEMENTED);
    }

}
